#!/bin/bash
url=${1:6}
echo $url
if [[ ! $url =~ ^https?:// ]]; then
  echo "protocol not allowed"
  exit 1
fi
mpv --fs --ytdl-format="bestvideo[ext!=webm][height<=?1080]‌​+bestaudio[ext!=webm]‌​/best[ext!=webm]" "$url"
