#!/bin/bash

# extract protocol, e.g. vlc, vlca, mpv, etc.
protocol=$( echo "${1%%:*}" )

# extract the actual url of the video, remaining part after the protocol
url=$( echo "${1#*//}" )

# detect which platform the script is running on
if echo "$( uname -a )" | grep -q "buntu"; then
    # it's ubuntu (desktop)
    case ${protocol} in
        vlc)
            # open video in VLC player
            vlc -f "${url}"
        ;;

        vlca)
            # open audio only in VLC player
            url=$( youtube-dl --get-url --format "bestaudio[ext!=webm]‌​" "${url}" )
            vlc --qt-start-minimized "${url}"
        ;;

        mpv)
            # open video in MPV player
            mpv --fs --ytdl-format="bestvideo[ext!=webm][vcodec^=avc1][height<=?1080]‌​+bestaudio[ext!=webm]‌​/best[ext!=webm]" "${url}"
        ;;

        ytm4a)
            # download m4a audio with youtube-dl
            youtube-dl --format "bestaudio[ext!=webm]" -o "~/Music/%(title)s.%(ext)s" "${url}"
        ;;

        yt720)
            # download 720p mp4 video with youtube-dl
            youtube-dl --format "bestvideo[ext!=webm][vcodec^=avc1][height<=?720]‌​+bestaudio[ext!=webm]‌​/best[ext!=webm]" -o "~/Videos/%(title)s.720p.%(ext)s" "${url}"
        ;;

        yt1080)
            # download 1080p mp4 video with youtube-dl
            youtube-dl --format "bestvideo[ext!=webm][vcodec^=avc1][height<=?1080]‌​+bestaudio[ext!=webm]‌​/best[ext!=webm]" -o "~/Videos/%(title)s.1080p.%(ext)s" "${url}"
        ;;

        *)
            exit 1
    esac
else
    # it's probably sailfish os
    # TinyTinyRSS for some reason does not pass the url correctly,
    # it passes https// instead of https:// (skips the colon).
    # this needs to be corrected
    if ! echo "${url}" | grep -q "://"; then
        url=$( echo "${url}" | sed 's/\/\//:\/\//')
    fi

    if [[ ${protocol} == "vlca" ]]; then
        # play audio only
        url=$( youtube-dl --get-url --format "bestaudio[ext!=webm]" "${url}" )
    else
        # play video
        url=$( youtube-dl --get-url --format "best[ext!=webm][height<=?720]" "${url}" )
    fi

    harbour-videoPlayer "${url}"
fi
